version: "3.1"

services:

  postgres:
    container_name: postgresdb
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock-data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

  djs:
    build:
      context: ../backend
    depends_on:
      - postgres
    image: djs
    ports:
      - "8080:8080"
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://postgres:5432/stock-data
      - spring.liquibase.url=jdbc:postgresql://postgres:5432/stock-data

volumes:
  postgres_data:
